#ifndef BIT_MATH_H_
#define BIT_MATH_H_

#define SET_BIT(VAR, BIT_NUMBER) (VAR|=(1<<BIT_NUMBER))

#define CLEAR_BIT(VAR, BIT_NUMBER) (VAR&=(~(1<<BIT_NUMBER)))

#define TOGGLE_BIT(VAR, BIT_NUMBER) (VAR^=(1<<BIT_NUMBER))

#define GET_BIT(VAR, BIT_NUMBER) (((VAR>>BIT_NUMBER)&1))

#endif 